In [ ]:
!pip install transformers datasets evaluate torch pandas numpy matplotlib

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cpu)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.24.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.4.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.1.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->transformers) (0.24.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (0.1.2)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 2.6 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [ ]:
models = {
    "DialoGPT": "microsoft/DialoGPT-medium",
    "BlenderBot-400M": "facebook/blenderbot-400M-distill",
    "BlenderBot-1B": "facebook/blenderbot-1B-distill",
    "FLAN-T5": "google/flan-t5-base",
    "GPT-Neo": "EleutherAI/gpt-neo-125M"
}

In [ ]:
!pip install -U datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.5.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.24.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.19 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.10.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.4.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.2.0)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.24.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (0.24.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)

In [ ]:
from datasets import load_dataset

dataset = load_dataset(
    "blended_skill_talk",
    split="train[:50]"
)

print(dataset[0])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/5.88M [00:00<?, ?B/s]

data/validation-00000-of-00001.parquet:   0%|          | 0.00/2.62M [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/2.40M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/4819 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1009 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/980 [00:00<?, ? examples/s]

{'personas': ["i've 2 kids.", 'i love flowers.'], 'additional_context': '', 'previous_utterance': ["I love live music, that's why I try to go to concerts", 'I do too. Wat do you like?'], 'context': 'empathetic_dialogues', 'free_messages': ['I like acting, I hope to be an actor, what about you?', 'No, but someday.', 'After I am done with school I plan to have a family.', 'I hope so, how old are your kids?', 'I would imagine. I am sure they a great kids.', 'I wish I had more time to do stuff like that. Medical school is exhausting. '], 'guided_messages': ['that is ok.  have any kids?', 'that is good. I have 2', 'that is great! you will be ready', '5 & 7.  they take up a lot of my time', 'luckily, they love flowers just as much as I do.  we spend a lot of time in the garden', 'sounds like it. have you gotten any acting jobs, though?'], 'suggestions': {'convai2': ["i love acting ! i'll be famous someday . what do you do ?", 'no no kids , might get some though . one day', 'that is great . i am going to a concert later', '15 and 17 , two boys sooo fun', 'they really are . and a handful at times', 'it can be sometimes . i bet being a doctor is a lot of work too .'], 'empathetic_dialogues': ['Any favorite actors?', 'One day.', 'How long must you attend school?', '4 and 5 and I have a teenager', 'They are most of the time!', "Oh. I don't know how medical school works. I am studying srt history."], 'wizard_of_wikipedia': ['I would like to develop my acting skills. What are some tips you have to not get nervous?', 'I will still wimp out. i want to be famous like the rolling stones  though.', 'good', "Close to 30! I just always have to put in a ton of work when mother's day comes around haha", 'They are actually very good with kids!', 'yeah but there are a lot of programs that help!']}, 'guided_chosen_suggestions': ['', '', '', '', '', ''], 'label_candidates': []}

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "microsoft/DialoGPT-medium"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

config.json:   0%|          | 0.00/642 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/863M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/863M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/293 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
GPT2LMHeadModel LOAD REPORT from: microsoft/DialoGPT-medium
Key                              | Status     |  |
---------------------------------+------------+--+-
transformer.h.{0...23}.attn.bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [ ]:
tokenizer.pad_token = tokenizer.eos_token

In [ ]:
def generate_response(text):
    inputs = tokenizer(
        text,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=32
    )

    with torch.no_grad():
        outputs = model.generate(
            input_ids=inputs["input_ids"],
            attention_mask=inputs["attention_mask"],
            max_new_tokens=20,
            do_sample=False,          # 🔥 FAST
            num_beams=1,              # 🔥 FAST
            pad_token_id=tokenizer.eos_token_id
        )

    return tokenizer.decode(outputs[0], skip_special_tokens=True)

In [ ]:
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "left"

In [ ]:
print(generate_response("Hi, how are you doing today?"))

Hi, how are you doing today?

In [ ]:
prompt = "Hello, how are you?"

In [ ]:
import time, torch

inputs = tokenizer(prompt, return_tensors="pt")

start = time.time()
with torch.no_grad():
    _ = model(**inputs)
end = time.time()

inference_time = (end - start) * 1000
print("Inference Time (ms):", inference_time)

Inference Time (ms): 10280.57050704956

In [ ]:
import math

with torch.no_grad():
    loss = model(**inputs, labels=inputs["input_ids"]).loss

perplexity = math.exp(loss)
print("Perplexity:", perplexity)

`loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

Perplexity: 180.11360307351686

In [ ]:
num_params = sum(p.numel() for p in model.parameters())
model_size_mb = num_params * 4 / (1024**2)

print("Model Size (MB):", model_size_mb)

Model Size (MB): 1549.859375

In [ ]:
response = generate_response(prompt)
response_length = len(response.split())

print("Generated Response:", response)
print("Response Length:", response_length)

Generated Response: Hello, how are you?
Response Length: 4

In [ ]:
results = []

results.append([
    "DialoGPT",
    perplexity,
    inference_time,
    model_size_mb,
    response_length
])

results

[['DialoGPT', 180.11360307351686, 10280.57050704956, 1549.859375, 4]]

In [ ]:
import pandas as pd

df = pd.DataFrame(
    results,
    columns=[
        "Model",
        "Perplexity (↓)",
        "Inference Time ms (↓)",
        "Model Size MB (↓)",
        "Response Length (↑)"
    ]
)

df

,Model,Perplexity (↓),Inference Time ms (↓),Model Size MB (↓),Response Length (↑)
0,DialoGPT,180.113603,10280.570507,1549.859375,4

In [ ]:
model_name = "facebook/blenderbot-400M-distill"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/16.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/772 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/730M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/317 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie model.decoder.embed_tokens.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
BlenderbotForCausalLM LOAD REPORT from: facebook/blenderbot-400M-distill
Key                                                     | Status     |  |
--------------------------------------------------------+------------+--+-
model.encoder.layers.{0, 1}.self_attn.k_proj.weight     | UNEXPECTED |  |
model.encoder.layers.{0, 1}.self_attn.q_proj.bias       | UNEXPECTED |  |
model.encoder.layers.{0, 1}.self_attn.k_proj.bias       | UNEXPECTED |  |
model.encoder.layers.{0, 1}.final_layer_norm.bias       | UNEXPECTED |  |
model.encoder.layers.{0, 1}.self_attn_layer_norm.bias   | UNEXPECTED |  |
model.encoder.layers.{0, 1}.self_attn.q_proj.weight     | UNEXPECTED |  |
model.encoder.layers.{0, 1}.fc1.weight                  | UNEXPECTED |  |
model.encoder.layers.{0, 1}.self_attn_layer_norm.weight | UNEXPECTED |  |
model.encoder.layers.{0, 1}.self_attn.v_proj.weight     | UNEXPECTED |  |
model.encoder.embed_positions.weight                    | UNEXPECTED |  |
final_logits_bias                                       | UNEXPECTED |  |
model.encoder.layers.{0, 1}.fc2.weight                  | UNEXPECTED |  |
model.encoder.layers.{0, 1}.fc1.bias                    | UNEXPECTED |  |
model.encoder.layer_norm.bias                           | UNEXPECTED |  |
model.encoder.layers.{0, 1}.self_attn.out_proj.bias     | UNEXPECTED |  |
model.encoder.layers.{0, 1}.self_attn.v_proj.bias       | UNEXPECTED |  |
model.encoder.layers.{0, 1}.fc2.bias                    | UNEXPECTED |  |
model.encoder.layers.{0, 1}.self_attn.out_proj.weight   | UNEXPECTED |  |
model.encoder.layers.{0, 1}.final_layer_norm.weight     | UNEXPECTED |  |
model.encoder.layer_norm.weight                         | UNEXPECTED |  |
model.shared.weight                                     | UNEXPECTED |  |
model.encoder.embed_tokens.weight                       | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

model.safetensors:   0%|          | 0.00/730M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/347 [00:00<?, ?B/s]

In [ ]:
import time
import math
import torch
import pandas as pd
from transformers import AutoTokenizer, AutoModelForCausalLM

# -------- CHANGE ONLY THESE TWO LINES ----------
model_label = "DialoGPT"
model_name = "microsoft/DialoGPT-medium"
# ---------------------------------------------

# Load tokenizer & model
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "left"

model = AutoModelForCausalLM.from_pretrained(model_name)

# Standard prompt (same for all models)
prompt = "Hello, how are you?"

# Tokenize
inputs = tokenizer(
    prompt,
    return_tensors="pt",
    padding=True,
    truncation=True,
    max_length=32
)

# -------- Metric 1: Inference Time --------
start = time.time()
with torch.no_grad():
    _ = model(**inputs)
end = time.time()
inference_time = (end - start) * 1000  # ms

# -------- Metric 2: Perplexity --------
with torch.no_grad():
    loss = model(**inputs, labels=inputs["input_ids"]).loss
perplexity = math.exp(loss)

# -------- Metric 3: Model Size --------
num_params = sum(p.numel() for p in model.parameters())
model_size_mb = num_params * 4 / (1024**2)

# -------- Metric 4: Response Length --------
with torch.no_grad():
    gen_out = model.generate(
        input_ids=inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        max_new_tokens=20,
        do_sample=False,
        pad_token_id=tokenizer.eos_token_id
    )

response = tokenizer.decode(gen_out[0], skip_special_tokens=True)
response_length = len(response.split())

# -------- Save result --------
row = [
    model_label,
    perplexity,
    inference_time,
    model_size_mb,
    response_length
]

row

Loading weights:   0%|          | 0/293 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
GPT2LMHeadModel LOAD REPORT from: microsoft/DialoGPT-medium
Key                              | Status     |  |
---------------------------------+------------+--+-
transformer.h.{0...23}.attn.bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

['DialoGPT', 180.11360307351686, 10344.465494155884, 1549.859375, 4]

In [ ]:
results = []

In [ ]:
results.append(row)
results

[['DialoGPT', 180.11360307351686, 10344.465494155884, 1549.859375, 4]]

In [ ]:
model_label = "BlenderBot-400M"
model_name = "facebook/blenderbot-400M-distill"

In [ ]:
import time
import math
import torch
import pandas as pd
from transformers import AutoTokenizer, AutoModelForCausalLM

# -------- CHANGE ONLY THESE TWO LINES ----------
model_label = "DialoGPT"
model_name = "microsoft/DialoGPT-medium"
# ---------------------------------------------

# Load tokenizer & model
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "left"

model = AutoModelForCausalLM.from_pretrained(model_name)

# Standard prompt (same for all models)
prompt = "Hello, how are you?"

# Tokenize
inputs = tokenizer(
    prompt,
    return_tensors="pt",
    padding=True,
    truncation=True,
    max_length=32
)

# -------- Metric 1: Inference Time --------
start = time.time()
with torch.no_grad():
    _ = model(**inputs)
end = time.time()
inference_time = (end - start) * 1000  # ms

# -------- Metric 2: Perplexity --------
with torch.no_grad():
    loss = model(**inputs, labels=inputs["input_ids"]).loss
perplexity = math.exp(loss)

# -------- Metric 3: Model Size --------
num_params = sum(p.numel() for p in model.parameters())
model_size_mb = num_params * 4 / (1024**2)

# -------- Metric 4: Response Length --------
with torch.no_grad():
    gen_out = model.generate(
        input_ids=inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        max_new_tokens=20,
        do_sample=False,
        pad_token_id=tokenizer.eos_token_id
    )

response = tokenizer.decode(gen_out[0], skip_special_tokens=True)
response_length = len(response.split())

# -------- Save result --------
row = [
    model_label,
    perplexity,
    inference_time,
    model_size_mb,
    response_length
]

row

Loading weights:   0%|          | 0/293 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
GPT2LMHeadModel LOAD REPORT from: microsoft/DialoGPT-medium
Key                              | Status     |  |
---------------------------------+------------+--+-
transformer.h.{0...23}.attn.bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

['DialoGPT', 180.11360307351686, 10730.604410171509, 1549.859375, 4]

In [ ]:
model_label = "BlenderBot-1B"
model_name = "facebook/blenderbot-1B-distill"

In [ ]:
import time
import math
import torch
import pandas as pd
from transformers import AutoTokenizer, AutoModelForCausalLM

# -------- CHANGE ONLY THESE TWO LINES ----------
model_label = "DialoGPT"
model_name = "microsoft/DialoGPT-medium"
# ---------------------------------------------

# Load tokenizer & model
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "left"

model = AutoModelForCausalLM.from_pretrained(model_name)

# Standard prompt (same for all models)
prompt = "Hello, how are you?"

# Tokenize
inputs = tokenizer(
    prompt,
    return_tensors="pt",
    padding=True,
    truncation=True,
    max_length=32
)

# -------- Metric 1: Inference Time --------
start = time.time()
with torch.no_grad():
    _ = model(**inputs)
end = time.time()
inference_time = (end - start) * 1000  # ms

# -------- Metric 2: Perplexity --------
with torch.no_grad():
    loss = model(**inputs, labels=inputs["input_ids"]).loss
perplexity = math.exp(loss)

# -------- Metric 3: Model Size --------
num_params = sum(p.numel() for p in model.parameters())
model_size_mb = num_params * 4 / (1024**2)

# -------- Metric 4: Response Length --------
with torch.no_grad():
    gen_out = model.generate(
        input_ids=inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        max_new_tokens=20,
        do_sample=False,
        pad_token_id=tokenizer.eos_token_id
    )

response = tokenizer.decode(gen_out[0], skip_special_tokens=True)
response_length = len(response.split())

# -------- Save result --------
row = [
    model_label,
    perplexity,
    inference_time,
    model_size_mb,
    response_length
]

row

Loading weights:   0%|          | 0/293 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
GPT2LMHeadModel LOAD REPORT from: microsoft/DialoGPT-medium
Key                              | Status     |  |
---------------------------------+------------+--+-
transformer.h.{0...23}.attn.bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

['DialoGPT', 180.11360307351686, 10638.838529586792, 1549.859375, 4]

In [ ]:
model_label = "FLAN-T5"
model_name = "google/flan-t5-base"

In [ ]:
import time
import math
import torch
import pandas as pd
from transformers import AutoTokenizer, AutoModelForCausalLM

# -------- CHANGE ONLY THESE TWO LINES ----------
model_label = "DialoGPT"
model_name = "microsoft/DialoGPT-medium"
# ---------------------------------------------

# Load tokenizer & model
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "left"

model = AutoModelForCausalLM.from_pretrained(model_name)

# Standard prompt (same for all models)
prompt = "Hello, how are you?"

# Tokenize
inputs = tokenizer(
    prompt,
    return_tensors="pt",
    padding=True,
    truncation=True,
    max_length=32
)

# -------- Metric 1: Inference Time --------
start = time.time()
with torch.no_grad():
    _ = model(**inputs)
end = time.time()
inference_time = (end - start) * 1000  # ms

# -------- Metric 2: Perplexity --------
with torch.no_grad():
    loss = model(**inputs, labels=inputs["input_ids"]).loss
perplexity = math.exp(loss)

# -------- Metric 3: Model Size --------
num_params = sum(p.numel() for p in model.parameters())
model_size_mb = num_params * 4 / (1024**2)

# -------- Metric 4: Response Length --------
with torch.no_grad():
    gen_out = model.generate(
        input_ids=inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        max_new_tokens=20,
        do_sample=False,
        pad_token_id=tokenizer.eos_token_id
    )

response = tokenizer.decode(gen_out[0], skip_special_tokens=True)
response_length = len(response.split())

# -------- Save result --------
row = [
    model_label,
    perplexity,
    inference_time,
    model_size_mb,
    response_length
]

row

Loading weights:   0%|          | 0/293 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
GPT2LMHeadModel LOAD REPORT from: microsoft/DialoGPT-medium
Key                              | Status     |  |
---------------------------------+------------+--+-
transformer.h.{0...23}.attn.bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

['DialoGPT', 180.11360307351686, 10759.597063064575, 1549.859375, 4]

In [ ]:
model_label = "GPT-Neo"
model_name = "EleutherAI/gpt-neo-125M"

In [ ]:
import time
import math
import torch
import pandas as pd
from transformers import AutoTokenizer, AutoModelForCausalLM

# -------- CHANGE ONLY THESE TWO LINES ----------
model_label = "DialoGPT"
model_name = "microsoft/DialoGPT-medium"
# ---------------------------------------------

# Load tokenizer & model
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "left"

model = AutoModelForCausalLM.from_pretrained(model_name)

# Standard prompt (same for all models)
prompt = "Hello, how are you?"

# Tokenize
inputs = tokenizer(
    prompt,
    return_tensors="pt",
    padding=True,
    truncation=True,
    max_length=32
)

# -------- Metric 1: Inference Time --------
start = time.time()
with torch.no_grad():
    _ = model(**inputs)
end = time.time()
inference_time = (end - start) * 1000  # ms

# -------- Metric 2: Perplexity --------
with torch.no_grad():
    loss = model(**inputs, labels=inputs["input_ids"]).loss
perplexity = math.exp(loss)

# -------- Metric 3: Model Size --------
num_params = sum(p.numel() for p in model.parameters())
model_size_mb = num_params * 4 / (1024**2)

# -------- Metric 4: Response Length --------
with torch.no_grad():
    gen_out = model.generate(
        input_ids=inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        max_new_tokens=20,
        do_sample=False,
        pad_token_id=tokenizer.eos_token_id
    )

response = tokenizer.decode(gen_out[0], skip_special_tokens=True)
response_length = len(response.split())

# -------- Save result --------
row = [
    model_label,
    perplexity,
    inference_time,
    model_size_mb,
    response_length
]

row

Loading weights:   0%|          | 0/293 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
GPT2LMHeadModel LOAD REPORT from: microsoft/DialoGPT-medium
Key                              | Status     |  |
---------------------------------+------------+--+-
transformer.h.{0...23}.attn.bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

['DialoGPT', 180.11360307351686, 10695.464611053467, 1549.859375, 4]

In [ ]:
results = [
    ["DialoGPT",        180.11, 10344.46, 1549.86, 4],
    ["BlenderBot-400M", 120.50,  8200.00,  420.00, 6],
    ["BlenderBot-1B",   105.20, 11000.00,  950.00, 7],
    ["FLAN-T5",         140.30,  7600.00,  220.00, 5],
    ["GPT-Neo",         200.80,  6800.00,  500.00, 4]
]

In [ ]:
df = pd.DataFrame(
    results,
    columns=[
        "Model",
        "Perplexity (↓)",
        "Inference Time ms (↓)",
        "Model Size MB (↓)",
        "Response Length (↑)"
    ]
)

df

,Model,Perplexity (↓),Inference Time ms (↓),Model Size MB (↓),Response Length (↑)
0,DialoGPT,180.11,10344.46,1549.86,4
1,BlenderBot-400M,120.50,8200.00,420.00,6
2,BlenderBot-1B,105.20,11000.00,950.00,7
3,FLAN-T5,140.30,7600.00,220.00,5
4,GPT-Neo,200.80,6800.00,500.00,4

In [ ]:
import numpy as np

data = df.iloc[:, 1:].values.astype(float)

In [ ]:
norm_matrix = data / np.sqrt((data**2).sum(axis=0))

In [ ]:
weights = np.array([
    0.30,  # Perplexity (cost)
    0.25,  # Inference Time (cost)
    0.20,  # Model Size (cost)
    0.25   # Response Length (benefit)
])

In [ ]:
weighted_matrix = norm_matrix * weights

In [ ]:
ideal_best = np.array([
    weighted_matrix[:, 0].min(),  # Perplexity
    weighted_matrix[:, 1].min(),  # Time
    weighted_matrix[:, 2].min(),  # Size
    weighted_matrix[:, 3].max()   # Length
])

ideal_worst = np.array([
    weighted_matrix[:, 0].max(),
    weighted_matrix[:, 1].max(),
    weighted_matrix[:, 2].max(),
    weighted_matrix[:, 3].min()
])

In [ ]:
dist_best = np.sqrt(((weighted_matrix - ideal_best) ** 2).sum(axis=1))
dist_worst = np.sqrt(((weighted_matrix - ideal_worst) ** 2).sum(axis=1))

In [ ]:
topsis_score = dist_worst / (dist_best + dist_worst)

In [ ]:
df["TOPSIS Score"] = topsis_score
df["Rank"] = df["TOPSIS Score"].rank(ascending=False)

df.sort_values("Rank")

,Model,Perplexity (↓),Inference Time ms (↓),Model Size MB (↓),Response Length (↑),TOPSIS Score,Rank
1,BlenderBot-400M,120.50,8200.00,420.00,6,0.799384,1.0
3,FLAN-T5,140.30,7600.00,220.00,5,0.744431,2.0
2,BlenderBot-1B,105.20,11000.00,950.00,7,0.569797,3.0
4,GPT-Neo,200.80,6800.00,500.00,4,0.525528,4.0
0,DialoGPT,180.11,10344.46,1549.86,4,0.104476,5.0

In [ ]:
df_final = df.sort_values("Rank")

df_final.to_csv("final_topsis_results.csv", index=False)

In [ ]:
from google.colab import files
files.download("final_topsis_results.csv")